// Generated by CoffeeScript 1.7.1
(function() {
  var getSession, getSubject;

  this.Active_Brain = {};

  getSession = function() {
    return $.ajax("/session");
  };

  getSubject = function() {
    return $.getJSON("/subject");
  };

  Active_Brain.teststart = (function(_this) {
    return function() {
      return RAT.start(1, 1).then(function() {
        return ArrowFlanker.start(1, 1);
      }).then(function() {
        return TrailsB.start(1, 1);
      }).then(function() {
        return AST.start(1, 1);
      });
    };
  })(this);

  Active_Brain.start = (function(_this) {
    return function() {
      return getSession().then(function(session) {
          _this.session = session;
          return getSubject();
        }).then(function(s) {
          var session, subject;
          _this.subject = s;
          session = _this.session.ID;
          subject = _this.subject.ID;
          return AST.start(session, subject).then(function() {
            return ArrowFlanker.start(session, subject);
          }).then(function() {
            return TrailsB.start(session, subject);
          }).then(function() {
            return RAT.start(session, subject);
          });
        })
        .fail(function(e) {
          console.log(e);
        });
    };
  })(this);

}).call(this);